Scheduler: servlets.Assign Class Reference
servlets.Assign Class Reference
Public Member Functions
Assign ()
Protected Member Functions
void doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
void doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
Constructor & Destructor Documentation
Assign()
servlets.Assign.Assign ()
Member Function Documentation
doGet()
void servlets.Assign.doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
doPost()
void servlets.Assign.doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
References DB.BackupDB.assignSection(), entities.Section.getCourseId(), and entities.Section.getSection().
The documentation for this class was generated from the following file:
src/main/java/servlets/Assign.java