Scheduler: servlets.Log Class Reference
servlets.Log Class Reference
Public Member Functions
Log ()
Protected Member Functions
void doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
void doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
Constructor & Destructor Documentation
Log()
servlets.Log.Log ()
Member Function Documentation
doGet()
void servlets.Log.doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
doPost()
void servlets.Log.doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
References DB.BackupDB.getAccount(), entities.Account.setPassword(), entities.Account.setUserName(), and DB.BackupDB.validate().
The documentation for this class was generated from the following file:
src/main/java/servlets/Log.java