Scheduler: entities.Schedule Class Reference
entities.Schedule Class Reference
Public Member Functions
Schedule ()
Schedule (int id, String courseId, String section, String method, int enroll, String instructor, String day, String startTime, String endTime, String room)
Schedule (String courseId, String section, String method, int enroll, String instructor, String day, String startTime, String endTime, String room)
Schedule (String day, String startTime, String endTime)
Schedule (String course, String section)
Schedule (String courseId, String section, String instructor, String day)
String getRoom ()
void setRoom (String room)
String getMethod ()
void setMethod (String method)
int getEnroll ()
void setEnroll (int enroll)
String getCourse ()
void setCourse (String courseId)
String getInstructor ()
void setInstructor (String instructor)
String getDay ()
void setDate (String day)
String getStartTime ()
String getEndTime ()
void setStartTime (String startTime)
void setSection (String section)
String setEndTime (String endTime)
String getSection ()
int getId ()
int setId (int id)
Detailed Description
CREATE TABLE Schedule (
id int Auto increment NOT NULL, courseId varchar(), sectId int, method varchar() NOT NULL, enroll int NOT NULL, instructor varchar(), day varchar(50) NOT NULL, start varchar(), end varchar(), room int NOT NULL, FOREIGN KEY(sectionId) REFERENCES Course(sectionId), FOREIGN KEY(room) REFERENCES Classroom(Id), FOREIGN KEY(courseId) REFERENCES Course(Id), PRIMARY KEY (id));
Constructor & Destructor Documentation
Schedule() [1/6]
entities.Schedule.Schedule ()
Schedule() [2/6]
entities.Schedule.Schedule (int id, String courseId, String section, String method, int enroll, String instructor, String day, String startTime, String endTime, String room)
Schedule() [3/6]
entities.Schedule.Schedule (String courseId, String section, String method, int enroll, String instructor, String day, String startTime, String endTime, String room)
Schedule() [4/6]
entities.Schedule.Schedule (String day, String startTime, String endTime)
Schedule() [5/6]
entities.Schedule.Schedule (String course, String section)
Schedule() [6/6]
entities.Schedule.Schedule (String courseId, String section, String instructor, String day)
Member Function Documentation
getCourse()
String entities.Schedule.getCourse ()
Referenced by DB.BackupDB.Assign(), and DB.BackupDB.saveSchedule().
getDay()
String entities.Schedule.getDay ()
Referenced by DB.BackupDB.saveSchedule().
getEndTime()
String entities.Schedule.getEndTime ()
Referenced by DB.BackupDB.saveSchedule().
getEnroll()
int entities.Schedule.getEnroll ()
Referenced by DB.BackupDB.Assign(), DB.BackupDB.assignSection(), DB.BackupDB.saveSchedule(), DB.BackupDB.saveSection(), and DB.BackupDB.updateSection().
getId()
int entities.Schedule.getId ()
getInstructor()
String entities.Schedule.getInstructor ()
Referenced by DB.BackupDB.Assign(), DB.BackupDB.assignSection(), DB.BackupDB.saveSchedule(), DB.BackupDB.saveSection(), and DB.BackupDB.updateSection().
getMethod()
String entities.Schedule.getMethod ()
Referenced by DB.BackupDB.Assign(), DB.BackupDB.assignSection(), DB.BackupDB.saveSchedule(), DB.BackupDB.saveSection(), and DB.BackupDB.updateSection().
getRoom()
String entities.Schedule.getRoom ()
Referenced by DB.BackupDB.saveSchedule().
getSection()
String entities.Schedule.getSection ()
Referenced by DB.BackupDB.Assign(), DB.BackupDB.assignSection(), DB.BackupDB.saveSchedule(), DB.BackupDB.saveSection(), and DB.BackupDB.updateSection().
getStartTime()
String entities.Schedule.getStartTime ()
Referenced by DB.BackupDB.saveSchedule().
setCourse()
void entities.Schedule.setCourse (String courseId)
Referenced by DB.BackupDB.ListSchedule().
setDate()
void entities.Schedule.setDate (String day)
Referenced by DB.BackupDB.getAvailableRooms(), DB.BackupDB.getUnavailableRooms(), and DB.BackupDB.ListSchedule().
setEndTime()
String entities.Schedule.setEndTime (String endTime)
Referenced by DB.BackupDB.getAvailableRooms(), DB.BackupDB.getUnavailableRooms(), and DB.BackupDB.ListSchedule().
setEnroll()
void entities.Schedule.setEnroll (int enroll)
setId()
int entities.Schedule.setId (int id)
Referenced by DB.BackupDB.ListSchedule().
setInstructor()
void entities.Schedule.setInstructor (String instructor)
Referenced by DB.BackupDB.ListSchedule().
setMethod()
void entities.Schedule.setMethod (String method)
setRoom()
void entities.Schedule.setRoom (String room)
Referenced by DB.BackupDB.getAvailableRooms(), DB.BackupDB.getUnavailableRooms(), and DB.BackupDB.ListSchedule().
setSection()
void entities.Schedule.setSection (String section)
Referenced by DB.BackupDB.ListSchedule().
setStartTime()
void entities.Schedule.setStartTime (String startTime)
Referenced by DB.BackupDB.getAvailableRooms(), DB.BackupDB.getUnavailableRooms(), and DB.BackupDB.ListSchedule().
The documentation for this class was generated from the following file:
src/main/java/entities/Schedule.java