Scheduler: DB.BackupDB Class Reference
DB.BackupDB Class Reference
Public Member Functions
boolean createAccount (Account acc) throws SQLException
boolean ScheduleRoom (String roomId, String courseId, String sectionId, String instructor, String day, String startTime, String endTime) throws SQLException
boolean saveSection (Section sh) throws SQLException
boolean saveDB (Classroom cl) throws SQLException
boolean saveSchedule (Schedule sh) throws SQLException
boolean adjustCap (Classroom room) throws SQLException
boolean updateSchedule (Schedule shed) throws SQLException
boolean updateClass (Classroom room) throws SQLException
boolean updateSection (Section sh) throws SQLException
boolean deleteClass (Classroom room) throws SQLException
boolean deleteSchedule (Schedule shed) throws SQLException
boolean deleteSection (Section sec) throws SQLException
boolean cancelSchedule (String roomId, String courseId, String sectionId, String instructor, String day, String startTime, String endTime) throws SQLException
boolean validate (Account acc) throws SQLException
List< Classroom > listClassRoom () throws SQLException
List< Course > listCourse () throws SQLException
List< Schedule > ListSchedule () throws SQLException
List< Schedule > getUnavailableRooms (String day, String startTime, String endTime, String roomId) throws SQLException
List< Schedule > getAvailableRooms (String day, String startTime, String endTime, String roomId) throws SQLException
Classroom getClassRoom (String id) throws SQLException
Account getAccount (String username) throws SQLException
boolean getSchedule (String Day, String start, String end, String room) throws SQLException
List< Schedule > listClass () throws SQLException
List< Section > listSection (String section, String course) throws SQLException
void Assign () throws SQLException
boolean assignSection (Section sh) throws SQLException
void Import () throws SQLException
void ExportSchedule () throws SQLException
Protected Member Functions
void connect () throws SQLException
void disconnect () throws SQLException
Member Function Documentation
adjustCap()
boolean DB.BackupDB.adjustCap (Classroom room) throws SQLException
References DB.BackupDB.connect(), and DB.BackupDB.disconnect().
Referenced by servlets.adjustCapacity.doPost().
Assign()
void DB.BackupDB.Assign () throws SQLException
References DB.BackupDB.connect(), DB.BackupDB.disconnect(), entities.Schedule.getCourse(), entities.Schedule.getEnroll(), entities.Schedule.getInstructor(), entities.Schedule.getMethod(), and entities.Schedule.getSection().
assignSection()
boolean DB.BackupDB.assignSection (Section sh) throws SQLException
References DB.BackupDB.connect(), DB.BackupDB.disconnect(), entities.Schedule.getEnroll(), entities.Schedule.getInstructor(), entities.Schedule.getMethod(), and entities.Schedule.getSection().
Referenced by servlets.Assign.doPost().
cancelSchedule()
boolean DB.BackupDB.cancelSchedule (String roomId, String courseId, String sectionId, String instructor, String day, String startTime, String endTime) throws SQLException
References DB.BackupDB.connect().
connect()
void DB.BackupDB.connect () throws SQLException protected
Referenced by DB.BackupDB.adjustCap(), DB.BackupDB.Assign(), DB.BackupDB.assignSection(), DB.BackupDB.cancelSchedule(), DB.BackupDB.createAccount(), DB.BackupDB.deleteClass(), DB.BackupDB.deleteSchedule(), DB.BackupDB.deleteSection(), DB.BackupDB.ExportSchedule(), DB.BackupDB.getAccount(), DB.BackupDB.getAvailableRooms(), DB.BackupDB.getClassRoom(), DB.BackupDB.getSchedule(), DB.BackupDB.getUnavailableRooms(), DB.BackupDB.Import(), DB.BackupDB.listClass(), DB.BackupDB.listClassRoom(), DB.BackupDB.listCourse(), DB.BackupDB.ListSchedule(), DB.BackupDB.listSection(), DB.BackupDB.saveDB(), DB.BackupDB.saveSchedule(), DB.BackupDB.saveSection(), DB.BackupDB.ScheduleRoom(), DB.BackupDB.updateClass(), DB.BackupDB.updateSchedule(), DB.BackupDB.updateSection(), and DB.BackupDB.validate().
createAccount()
boolean DB.BackupDB.createAccount (Account acc) throws SQLException
References DB.BackupDB.connect(), and DB.BackupDB.disconnect().
Referenced by servlets.Register.doPost().
deleteClass()
boolean DB.BackupDB.deleteClass (Classroom room) throws SQLException
References DB.BackupDB.connect(), and DB.BackupDB.disconnect().
Referenced by servlets.removeClass.doPost().
deleteSchedule()
boolean DB.BackupDB.deleteSchedule (Schedule shed) throws SQLException
References DB.BackupDB.connect(), and DB.BackupDB.disconnect().
Referenced by servlets.removeSchedule.doPost().
deleteSection()
boolean DB.BackupDB.deleteSection (Section sec) throws SQLException
References DB.BackupDB.connect(), and DB.BackupDB.disconnect().
Referenced by servlets.removeSection.doPost().
disconnect()
void DB.BackupDB.disconnect () throws SQLException protected
Referenced by DB.BackupDB.adjustCap(), DB.BackupDB.Assign(), DB.BackupDB.assignSection(), DB.BackupDB.createAccount(), DB.BackupDB.deleteClass(), DB.BackupDB.deleteSchedule(), DB.BackupDB.deleteSection(), DB.BackupDB.listClass(), DB.BackupDB.listClassRoom(), DB.BackupDB.listCourse(), DB.BackupDB.listSection(), DB.BackupDB.saveDB(), DB.BackupDB.saveSchedule(), DB.BackupDB.saveSection(), DB.BackupDB.updateClass(), DB.BackupDB.updateSchedule(), and DB.BackupDB.updateSection().
ExportSchedule()
void DB.BackupDB.ExportSchedule () throws SQLException
References DB.BackupDB.connect().
getAccount()
Account DB.BackupDB.getAccount (String username) throws SQLException
References DB.BackupDB.connect(), and entities.Account.setUserName().
Referenced by servlets.Log.doPost(), and servlets.Register.doPost().
getAvailableRooms()
List< Schedule > DB.BackupDB.getAvailableRooms (String day, String startTime, String endTime, String roomId) throws SQLException
References DB.BackupDB.connect(), entities.Schedule.setDate(), entities.Schedule.setEndTime(), entities.Schedule.setRoom(), and entities.Schedule.setStartTime().
getClassRoom()
Classroom DB.BackupDB.getClassRoom (String id) throws SQLException
References DB.BackupDB.connect(), entities.Classroom.setId(), entities.Classroom.setSeats(), and entities.Classroom.setType().
getSchedule()
boolean DB.BackupDB.getSchedule (String Day, String start, String end, String room) throws SQLException
References DB.BackupDB.connect().
Referenced by servlets.addSchedule.doPost(), and servlets.updateSchedule.doPost().
getUnavailableRooms()
List< Schedule > DB.BackupDB.getUnavailableRooms (String day, String startTime, String endTime, String roomId) throws SQLException
References DB.BackupDB.connect(), entities.Schedule.setDate(), entities.Schedule.setEndTime(), entities.Schedule.setRoom(), and entities.Schedule.setStartTime().
Import()
void DB.BackupDB.Import () throws SQLException
References DB.BackupDB.connect().
Referenced by servlets.importServlet.doPost().
listClass()
List< Schedule > DB.BackupDB.listClass () throws SQLException
References DB.BackupDB.connect(), and DB.BackupDB.disconnect().
listClassRoom()
List< Classroom > DB.BackupDB.listClassRoom () throws SQLException
References DB.BackupDB.connect(), and DB.BackupDB.disconnect().
listCourse()
List< Course > DB.BackupDB.listCourse () throws SQLException
References DB.BackupDB.connect(), and DB.BackupDB.disconnect().
ListSchedule()
List< Schedule > DB.BackupDB.ListSchedule () throws SQLException
References DB.BackupDB.connect(), entities.Schedule.setCourse(), entities.Schedule.setDate(), entities.Schedule.setEndTime(), entities.Schedule.setId(), entities.Schedule.setInstructor(), entities.Schedule.setRoom(), entities.Schedule.setSection(), and entities.Schedule.setStartTime().
listSection()
List< Section > DB.BackupDB.listSection (String section, String course) throws SQLException
References DB.BackupDB.connect(), and DB.BackupDB.disconnect().
saveDB()
boolean DB.BackupDB.saveDB (Classroom cl) throws SQLException
References DB.BackupDB.connect(), and DB.BackupDB.disconnect().
Referenced by servlets.addRoom.doPost().
saveSchedule()
boolean DB.BackupDB.saveSchedule (Schedule sh) throws SQLException
References DB.BackupDB.connect(), DB.BackupDB.disconnect(), entities.Schedule.getCourse(), entities.Schedule.getDay(), entities.Schedule.getEndTime(), entities.Schedule.getEnroll(), entities.Schedule.getInstructor(), entities.Schedule.getMethod(), entities.Schedule.getRoom(), entities.Schedule.getSection(), and entities.Schedule.getStartTime().
Referenced by servlets.addSchedule.doPost().
saveSection()
boolean DB.BackupDB.saveSection (Section sh) throws SQLException
References DB.BackupDB.connect(), DB.BackupDB.disconnect(), entities.Schedule.getEnroll(), entities.Schedule.getInstructor(), entities.Schedule.getMethod(), and entities.Schedule.getSection().
Referenced by servlets.addSection.doPost().
ScheduleRoom()
boolean DB.BackupDB.ScheduleRoom (String roomId, String courseId, String sectionId, String instructor, String day, String startTime, String endTime) throws SQLException
References DB.BackupDB.connect().
updateClass()
boolean DB.BackupDB.updateClass (Classroom room) throws SQLException
References DB.BackupDB.connect(), and DB.BackupDB.disconnect().
Referenced by servlets.updateClass.doPost().
updateSchedule()
boolean DB.BackupDB.updateSchedule (Schedule shed) throws SQLException
References DB.BackupDB.connect(), and DB.BackupDB.disconnect().
Referenced by servlets.updateSchedule.doPost().
updateSection()
boolean DB.BackupDB.updateSection (Section sh) throws SQLException
References DB.BackupDB.connect(), DB.BackupDB.disconnect(), entities.Schedule.getEnroll(), entities.Schedule.getInstructor(), entities.Schedule.getMethod(), and entities.Schedule.getSection().
Referenced by servlets.updateSection.doPost().
validate()
boolean DB.BackupDB.validate (Account acc) throws SQLException
References DB.BackupDB.connect().
Referenced by servlets.Log.doPost().
The documentation for this class was generated from the following file:
src/main/java/DB/BackupDB.java