Scheduler: DB.Utils Class Reference
DB.Utils Class Reference
Public Member Functions
String register (Account acc) throws SQLException
List< Classroom > listClassRoom () throws SQLException
List< Course > listCourse () throws SQLException
List< Schedule > listSchedule () throws SQLException
boolean deleteDB (Classroom room) throws SQLException
boolean updateDB (Classroom room) throws SQLException
Account getAccount (String id) throws SQLException
boolean validate (Account acc) throws SQLException
Protected Member Functions
void connect () throws SQLException
Member Function Documentation
connect()
void DB.Utils.connect () throws SQLException protected
References DB.DBConnection.connection, and DB.DBConnection.getDBConnection().
Referenced by DB.Utils.deleteDB(), DB.Utils.getAccount(), DB.Utils.listClassRoom(), DB.Utils.listCourse(), DB.Utils.listSchedule(), DB.Utils.register(), DB.Utils.updateDB(), and DB.Utils.validate().
deleteDB()
boolean DB.Utils.deleteDB (Classroom room) throws SQLException
References DB.Utils.connect().
getAccount()
Account DB.Utils.getAccount (String id) throws SQLException
References DB.Utils.connect().
listClassRoom()
List< Classroom > DB.Utils.listClassRoom () throws SQLException
References DB.Utils.connect().
listCourse()
List< Course > DB.Utils.listCourse () throws SQLException
References DB.Utils.connect().
listSchedule()
List< Schedule > DB.Utils.listSchedule () throws SQLException
References DB.Utils.connect().
register()
String DB.Utils.register (Account acc) throws SQLException
References DB.Utils.connect().
updateDB()
boolean DB.Utils.updateDB (Classroom room) throws SQLException
References DB.Utils.connect().
validate()
boolean DB.Utils.validate (Account acc) throws SQLException
References DB.Utils.connect().
The documentation for this class was generated from the following file:
src/main/java/DB/Utils.java