ClassScheduler: entities.Enrollment Class Reference
entities.Enrollment Class Reference
Public Member Functions
Enrollment ()
Enrollment (String seat, String section, String year, String term)
String getSeats ()
void setSeats (String seat)
String getYear ()
void setYear (String year)
String getTerm ()
void setTerm (String term)
String getSection ()
Detailed Description
CREATE TABLE Enrollment (seat varchar() NOT NULL, sectionId varchar(), year varchar(), term varchar(), FOREIGN KEY(sectionId) REFERENCES Section(ID), PRIMARY KEY (seats));
Constructor & Destructor Documentation
Enrollment() [1/2]
entities.Enrollment.Enrollment ()
Enrollment() [2/2]
entities.Enrollment.Enrollment (String seat, String section, String year, String term)
Member Function Documentation
getSeats()
String entities.Enrollment.getSeats ()
Referenced by util.UtilSchedule.getActiveSchedules().
getSection()
String entities.Enrollment.getSection ()
Referenced by util.UtilEnrollment.listEnroll().
getTerm()
String entities.Enrollment.getTerm ()
getYear()
String entities.Enrollment.getYear ()
setSeats()
void entities.Enrollment.setSeats (String seat)
Referenced by util.UtilEnrollment.UpdateEnrollment().
setTerm()
void entities.Enrollment.setTerm (String term)
setYear()
void entities.Enrollment.setYear (String year)
The documentation for this class was generated from the following file:
C:/Users/tnangati/Desktop/Project/Capstone/Git/ClassScheduler/src/main/java/entities/Enrollment.java