ClassScheduler: entities.Account Class Reference
entities.Account Class Reference
Public Member Functions
Account ()
Account (String userName, String firstName, String lastName, String email, String password)
Account (String userName, String password)
int getId ()
void setId (int id)
String getUserName ()
void setUserName (String userName)
String getFirstName ()
void setFirstName (String firstName)
String getLastName ()
void setLastName (String lastName)
String getEmail ()
void setEmail (String email)
String getPassword ()
void setPassword (String password)
Detailed Description
CREATE TABLE Account (id varchar(50) NOT NULL Auto_increment, username varchar(45), firstname varchar(), lastname varchar(), email varchar(), password varchar(), PRIMARY KEY (id));
Constructor & Destructor Documentation
Account() [1/3]
entities.Account.Account ()
Account() [2/3]
entities.Account.Account (String userName, String firstName, String lastName, String email, String password)
Account() [3/3]
entities.Account.Account (String userName, String password)
Member Function Documentation
getEmail()
String entities.Account.getEmail ()
getFirstName()
String entities.Account.getFirstName ()
Referenced by util.UtilAccount.listAccounts(), util.UtilBuilding.listAccounts(), and util.UtilCourse.listAccounts().
getId()
int entities.Account.getId ()
getLastName()
String entities.Account.getLastName ()
getPassword()
String entities.Account.getPassword ()
Referenced by servlets.Login.doGet(), and util.UtilAccount.validate().
getUserName()
String entities.Account.getUserName ()
setEmail()
void entities.Account.setEmail (String email)
Referenced by servlets.Register.doGet().
setFirstName()
void entities.Account.setFirstName (String firstName)
Referenced by servlets.Register.doGet().
setId()
void entities.Account.setId (int id)
setLastName()
void entities.Account.setLastName (String lastName)
Referenced by servlets.Register.doGet().
setPassword()
void entities.Account.setPassword (String password)
Referenced by servlets.Register.doGet().
setUserName()
void entities.Account.setUserName (String userName)
Referenced by servlets.Register.doGet().
The documentation for this class was generated from the following file:
C:/Users/tnangati/Desktop/Project/Capstone/Git/ClassScheduler/src/main/java/entities/Account.java