ClassScheduler: util.UtilInstructor Class Reference
util.UtilInstructor Class Reference
Public Member Functions
void saveInstructor (Instructor in)
Static Public Member Functions
static List< Instructor > listInstruct ()
static List< Instructor > listInstructors (String keyword)
static Instructor getInstructor (String id)
static boolean addInstructor (String id, String firstName, String lastName, String dept)
static List< Instructor > getInstructorByName ()
static boolean removeInstructor (String id)
Static Public Member Functions inherited from util.Hibernate
static SessionFactory getSessionFactory ()
Member Function Documentation
addInstructor()
static boolean util.UtilInstructor.addInstructor (String id, String firstName, String lastName, String dept) static
References util.Hibernate.getSessionFactory().
getInstructor()
static Instructor util.UtilInstructor.getInstructor (String id) static
References util.Hibernate.getSessionFactory().
getInstructorByName()
static List< Instructor > util.UtilInstructor.getInstructorByName () static
References util.Hibernate.getSessionFactory().
Referenced by servlets.displayTable.doGet().
listInstruct()
static List< Instructor > util.UtilInstructor.listInstruct () static
References util.Hibernate.getSessionFactory().
listInstructors()
static List< Instructor > util.UtilInstructor.listInstructors (String keyword) static
References entities.Instructor.getFirstName(), and util.Hibernate.getSessionFactory().
removeInstructor()
static boolean util.UtilInstructor.removeInstructor (String id) static
References util.Hibernate.getSessionFactory().
saveInstructor()
void util.UtilInstructor.saveInstructor (Instructor in)
References util.Hibernate.getSessionFactory().
The documentation for this class was generated from the following file:
C:/Users/tnangati/Desktop/Project/Capstone/Git/ClassScheduler/src/main/java/util/UtilInstructor.java