ClassScheduler: util.UtilClass Class Reference
util.UtilClass Class Reference
Public Member Functions
Classroom getClass (String Id, String building)
Classroom getRoom (String Id)
boolean addClass (Classroom c)
void saveClass (Classroom cl)
void updateClass (Classroom room)
Static Public Member Functions
static List< Classroom > listClass ()
static List< Classroom > listClass (String keyword)
static List< Classroom > getClassById ()
static boolean addClassroom (String Id, String type, String building, String seats, String computers)
static boolean updateCapacity (String roomId, String seats)
static boolean removeClass (String Id)
Static Public Member Functions inherited from util.Hibernate
static SessionFactory getSessionFactory ()
Member Function Documentation
addClass()
boolean util.UtilClass.addClass (Classroom c)
References util.Hibernate.getSessionFactory().
addClassroom()
static boolean util.UtilClass.addClassroom (String Id, String type, String building, String seats, String computers) static
References util.Hibernate.getSessionFactory().
getClass()
Classroom util.UtilClass.getClass (String Id, String building)
References util.Hibernate.getSessionFactory().
getClassById()
static List< Classroom > util.UtilClass.getClassById () static
References util.Hibernate.getSessionFactory().
Referenced by servlets.displayTable.doGet().
getRoom()
Classroom util.UtilClass.getRoom (String Id)
References util.Hibernate.getSessionFactory().
Referenced by servlets.addRoom.doGet().
listClass() [1/2]
static List< Classroom > util.UtilClass.listClass () static
References util.Hibernate.getSessionFactory().
listClass() [2/2]
static List< Classroom > util.UtilClass.listClass (String keyword) static
References entities.Classroom.getId(), and util.Hibernate.getSessionFactory().
removeClass()
static boolean util.UtilClass.removeClass (String Id) static
References util.Hibernate.getSessionFactory().
saveClass()
void util.UtilClass.saveClass (Classroom cl)
References util.Hibernate.getSessionFactory().
Referenced by servlets.addRoom.doGet().
updateCapacity()
static boolean util.UtilClass.updateCapacity (String roomId, String seats) static
References util.Hibernate.getSessionFactory(), and entities.Classroom.setSeats().
updateClass()
void util.UtilClass.updateClass (Classroom room)
References entities.Classroom.getId(), and util.Hibernate.getSessionFactory().
The documentation for this class was generated from the following file:
C:/Users/tnangati/Desktop/Project/Capstone/Git/ClassScheduler/src/main/java/util/UtilClass.java