ClassScheduler: util.UtilEnrollment Class Reference
util.UtilEnrollment Class Reference
Static Public Member Functions
static List< Enrollment > listEnroll ()
static List< Enrollment > listEnroll (String keyword)
static Enrollment getEnrollment (String seat)
static boolean UpdateEnrollment (String section, String seats)
Static Public Member Functions inherited from util.Hibernate
static SessionFactory getSessionFactory ()
Member Function Documentation
getEnrollment()
static Enrollment util.UtilEnrollment.getEnrollment (String seat) static
References util.Hibernate.getSessionFactory().
listEnroll() [1/2]
static List< Enrollment > util.UtilEnrollment.listEnroll () static
References util.Hibernate.getSessionFactory().
listEnroll() [2/2]
static List< Enrollment > util.UtilEnrollment.listEnroll (String keyword) static
References entities.Enrollment.getSection(), and util.Hibernate.getSessionFactory().
UpdateEnrollment()
static boolean util.UtilEnrollment.UpdateEnrollment (String section, String seats) static
References util.Hibernate.getSessionFactory(), and entities.Enrollment.setSeats().
The documentation for this class was generated from the following file:
C:/Users/tnangati/Desktop/Project/Capstone/Git/ClassScheduler/src/main/java/util/UtilEnrollment.java