ClassScheduler: util.UtilSection Class Reference
util.UtilSection Class Reference
Public Member Functions
void saveSection (Section sec)
Static Public Member Functions
static List< Section > listSection ()
static List< Section > listSections (String keyword)
static Section getSection (String Id)
static Section getSectionByCourse (String courseId)
static boolean addSection (String Id, String courseId, String type, String method, String enroll, String room, String instructor, String meeting, String term)
static boolean removeSection (String Id)
Static Public Member Functions inherited from util.Hibernate
static SessionFactory getSessionFactory ()
Member Function Documentation
addSection()
static boolean util.UtilSection.addSection (String Id, String courseId, String type, String method, String enroll, String room, String instructor, String meeting, String term) static
References util.Hibernate.getSessionFactory().
getSection()
static Section util.UtilSection.getSection (String Id) static
References util.Hibernate.getSessionFactory().
getSectionByCourse()
static Section util.UtilSection.getSectionByCourse (String courseId) static
References util.Hibernate.getSessionFactory().
listSection()
static List< Section > util.UtilSection.listSection () static
References util.Hibernate.getSessionFactory().
listSections()
static List< Section > util.UtilSection.listSections (String keyword) static
References entities.Section.getId(), and util.Hibernate.getSessionFactory().
removeSection()
static boolean util.UtilSection.removeSection (String Id) static
References util.Hibernate.getSessionFactory().
saveSection()
void util.UtilSection.saveSection (Section sec)
References util.Hibernate.getSessionFactory().
The documentation for this class was generated from the following file:
C:/Users/tnangati/Desktop/Project/Capstone/Git/ClassScheduler/src/main/java/util/UtilSection.java