ClassScheduler: servlets.displayTable Class Reference
servlets.displayTable Class Reference
Public Member Functions
displayTable ()
Protected Member Functions
void doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
void doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
Constructor & Destructor Documentation
displayTable()
servlets.displayTable.displayTable ()
Member Function Documentation
doGet()
void servlets.displayTable.doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
References util.UtilClass.getClassById(), util.UtilCourse.getCourseByTitle(), util.UtilInstructor.getInstructorByName(), and util.UtilSchedule.getSchedulesByDay().
doPost()
void servlets.displayTable.doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
See also
HttpServlet::doPost(HttpServletRequest request, HttpServletResponse response)
The documentation for this class was generated from the following file:
C:/Users/tnangati/Desktop/Project/Capstone/Git/ClassScheduler/src/main/java/servlets/displayTable.java