ClassScheduler: util.UtilSchedule Class Reference
util.UtilSchedule Class Reference
Public Member Functions
void saveSchedule (Schedule sh)
void updateSchedule (Schedule sh)
Static Public Member Functions
static List< Schedule > listSchedule ()
static List< Schedule > listSchedules (String keyword)
static Schedule addSchedule (Schedule sh)
static List< Schedule > getSchedulesByDay ()
static List< Schedule > getScheduleBySection (String sectionId)
static List< Schedule > getActiveSchedules (String sectionId)
static boolean addSchedule (String day, String start, String end)
static boolean updateSchedule (String day, String startTime, String endTime)
static boolean removeSchedule (String day, String startTime, String endTime, int sectionId)
Static Public Member Functions inherited from util.Hibernate
static SessionFactory getSessionFactory ()
Member Function Documentation
addSchedule() [1/2]
static Schedule util.UtilSchedule.addSchedule (Schedule sh) static
References util.Hibernate.getSessionFactory().
addSchedule() [2/2]
static boolean util.UtilSchedule.addSchedule (String day, String start, String end) static
References util.Hibernate.getSessionFactory().
getActiveSchedules()
static List< Schedule > util.UtilSchedule.getActiveSchedules (String sectionId) static
References entities.Enrollment.getSeats(), and util.Hibernate.getSessionFactory().
getScheduleBySection()
static List< Schedule > util.UtilSchedule.getScheduleBySection (String sectionId) static
References util.Hibernate.getSessionFactory().
getSchedulesByDay()
static List< Schedule > util.UtilSchedule.getSchedulesByDay () static
References util.Hibernate.getSessionFactory().
Referenced by servlets.displayTable.doGet().
listSchedule()
static List< Schedule > util.UtilSchedule.listSchedule () static
References util.Hibernate.getSessionFactory().
listSchedules()
static List< Schedule > util.UtilSchedule.listSchedules (String keyword) static
References entities.Schedule.getDay(), and util.Hibernate.getSessionFactory().
removeSchedule()
static boolean util.UtilSchedule.removeSchedule (String day, String startTime, String endTime, int sectionId) static
References util.Hibernate.getSessionFactory().
saveSchedule()
void util.UtilSchedule.saveSchedule (Schedule sh)
References util.Hibernate.getSessionFactory().
updateSchedule() [1/2]
void util.UtilSchedule.updateSchedule (Schedule sh)
References util.Hibernate.getSessionFactory().
updateSchedule() [2/2]
static boolean util.UtilSchedule.updateSchedule (String day, String startTime, String endTime) static
References util.Hibernate.getSessionFactory(), entities.Schedule.setDate(), entities.Schedule.setEndTime(), and entities.Schedule.setStartTime().
The documentation for this class was generated from the following file:
C:/Users/tnangati/Desktop/Project/Capstone/Git/ClassScheduler/src/main/java/util/UtilSchedule.java