ClassScheduler: servlets.Register Class Reference
servlets.Register Class Reference
Public Member Functions
Register ()
Protected Member Functions
void doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
void doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
Constructor & Destructor Documentation
Register()
servlets.Register.Register ()
Member Function Documentation
doGet()
void servlets.Register.doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
References util.UtilAccount.createAccounts(), util.UtilAccount.getAccount(), util.UtilAccount.saveAccount(), entities.Account.setEmail(), entities.Account.setFirstName(), entities.Account.setLastName(), entities.Account.setPassword(), and entities.Account.setUserName().
doPost()
void servlets.Register.doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
The documentation for this class was generated from the following file:
C:/Users/tnangati/Desktop/Project/Capstone/Git/ClassScheduler/src/main/java/servlets/Register.java