ClassScheduler: util.UtilAccount Class Reference
util.UtilAccount Class Reference
Public Member Functions
boolean validate (String username, String password)
void saveAccount (Account acc)
Static Public Member Functions
static List< Account > listAccounts ()
static List< Account > listAccounts (String keyword)
static Account getAccount (String username)
static boolean createAccounts (String username, String firstName, String lastName, String email, String password)
static void createAccount (String username, String firstname, String lastname, String email, String password)
Static Public Member Functions inherited from util.Hibernate
static SessionFactory getSessionFactory ()
Member Function Documentation
createAccount()
static void util.UtilAccount.createAccount (String username, String firstname, String lastname, String email, String password) static
References util.Hibernate.getSessionFactory().
createAccounts()
static boolean util.UtilAccount.createAccounts (String username, String firstName, String lastName, String email, String password) static
References util.Hibernate.getSessionFactory().
Referenced by servlets.Register.doGet().
getAccount()
static Account util.UtilAccount.getAccount (String username) static
References util.Hibernate.getSessionFactory().
Referenced by servlets.Login.doGet(), and servlets.Register.doGet().
listAccounts() [1/2]
static List< Account > util.UtilAccount.listAccounts () static
References util.Hibernate.getSessionFactory().
listAccounts() [2/2]
static List< Account > util.UtilAccount.listAccounts (String keyword) static
References entities.Account.getFirstName(), and util.Hibernate.getSessionFactory().
saveAccount()
void util.UtilAccount.saveAccount (Account acc)
References util.Hibernate.getSessionFactory().
Referenced by servlets.Register.doGet().
validate()
boolean util.UtilAccount.validate (String username, String password)
References entities.Account.getPassword(), and util.Hibernate.getSessionFactory().
The documentation for this class was generated from the following file:
C:/Users/tnangati/Desktop/Project/Capstone/Git/ClassScheduler/src/main/java/util/UtilAccount.java