ClassScheduler: entities.Classroom Class Reference
entities.Classroom Class Reference
Public Member Functions
Classroom ()
Classroom (String id, String type, String building, String seat, String computers)
Classroom (String id, String building, String seat)
String getId ()
void setId (String id)
String getType ()
void setType (String type)
String getBuilding ()
String getSeat ()
void setSeats (String seat)
String getComputers ()
void setComputers (String computers)
void setBuilding (String building)
Detailed Description
CREATE TABLE Class (id String varchar() NOT NULL, type varchar(100) NOT NULL, building VARCHAR (10), seat varchar() NOT NULL, computers varchar(), FOREIGN KEY(building) REFRENCES Building(ID), PRIMARY KEY (Id));
Constructor & Destructor Documentation
Classroom() [1/3]
entities.Classroom.Classroom ()
Classroom() [2/3]
entities.Classroom.Classroom (String id, String type, String building, String seat, String computers)
Classroom() [3/3]
entities.Classroom.Classroom (String id, String building, String seat)
Member Function Documentation
getBuilding()
String entities.Classroom.getBuilding ()
getComputers()
String entities.Classroom.getComputers ()
getId()
String entities.Classroom.getId ()
Referenced by util.UtilClass.listClass(), and util.UtilClass.updateClass().
getSeat()
String entities.Classroom.getSeat ()
getType()
String entities.Classroom.getType ()
setBuilding()
void entities.Classroom.setBuilding (String building)
Referenced by servlets.addRoom.doGet().
setComputers()
void entities.Classroom.setComputers (String computers)
Referenced by servlets.addRoom.doGet().
setId()
void entities.Classroom.setId (String id)
Referenced by servlets.addRoom.doGet().
setSeats()
void entities.Classroom.setSeats (String seat)
Referenced by servlets.addRoom.doGet(), and util.UtilClass.updateCapacity().
setType()
void entities.Classroom.setType (String type)
Referenced by servlets.addRoom.doGet().
The documentation for this class was generated from the following file:
C:/Users/tnangati/Desktop/Project/Capstone/Git/ClassScheduler/src/main/java/entities/Classroom.java