ClassScheduler: util.UtilBuilding Class Reference
util.UtilBuilding Class Reference
Static Public Member Functions
static List< Building > listBuilding ()
static List< Account > listAccounts (String keyword)
static Building getBuilding (String code)
Static Public Member Functions inherited from util.Hibernate
static SessionFactory getSessionFactory ()
Member Function Documentation
getBuilding()
static Building util.UtilBuilding.getBuilding (String code) static
References util.Hibernate.getSessionFactory().
listAccounts()
static List< Account > util.UtilBuilding.listAccounts (String keyword) static
References entities.Account.getFirstName(), and util.Hibernate.getSessionFactory().
listBuilding()
static List< Building > util.UtilBuilding.listBuilding () static
References util.Hibernate.getSessionFactory().
The documentation for this class was generated from the following file:
C:/Users/tnangati/Desktop/Project/Capstone/Git/ClassScheduler/src/main/java/util/UtilBuilding.java