ClassScheduler: util.UtilDepartment Class Reference
util.UtilDepartment Class Reference
Static Public Member Functions
static List< Department > listDepartment ()
static List< Department > listDepartments (String keyword)
static Department getDepartment (String code)
Static Public Member Functions inherited from util.Hibernate
static SessionFactory getSessionFactory ()
Member Function Documentation
getDepartment()
static Department util.UtilDepartment.getDepartment (String code) static
References util.Hibernate.getSessionFactory().
listDepartment()
static List< Department > util.UtilDepartment.listDepartment () static
References util.Hibernate.getSessionFactory().
listDepartments()
static List< Department > util.UtilDepartment.listDepartments (String keyword) static
References entities.Department.getName(), and util.Hibernate.getSessionFactory().
The documentation for this class was generated from the following file:
C:/Users/tnangati/Desktop/Project/Capstone/Git/ClassScheduler/src/main/java/util/UtilDepartment.java